# Sadly it looks like johnson does not support ruby 1.9.x and because
# it is a native extension it will likely have issues with jruby.
#
# Rubinius also seems to have issues.
rvm:
  - 1.8.7
  - ree

script: "bundle exec ruby test/suite.rb"

